#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm and set up the environment
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the correct Node.js version
nvm use 16

npm run lint-staged